name: Rust CI

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:

jobs:
  test-lint:
    runs-on: codeberg-medium

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: siebert/setup-rust@stable
        with:
          components: rustfmt

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --all --verbose

      - name: Rustfmt
        run: cargo fmt --all -- --check

  publish:
    needs: test-lint
    runs-on: codeberg-medium
    if: startsWith(forgejo.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: siebert/setup-rust@stable

      - name: Set version from tag
        run: |
          TAG_VERSION=${forgejo.ref#refs/tags/v}
          echo "Setting version to $TAG_VERSION in Cargo.toml"
          sed -i "s/^version = \".*\"/version = \"$TAG_VERSION\"/" Cargo.toml

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --locked
