name: Rust CI

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:

jobs:
  test-lint:
    runs-on: codeberg-medium

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --all --verbose

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Rustfmt
        run: cargo fmt --all -- --check

  publish:
    needs: test-lint
    runs-on: codeberg-medium
    if: startsWith(gitea.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --locked
